import { Anggota, Pengguna } from './types';

export const INITIAL_ANGGOTA: Anggota[] = [
  {
    id: '1',
    nama: 'Yohanes Mayor',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN KOTAWI',
    tanggalLahir: '1998-04-12',
    telepon: '081234567890',
    alamat: 'Waisai, Jl. Port Kotawi',
    status: 'Aktif',
    tanggalDaftar: '2024-01-10',
  },
  {
    id: '2',
    nama: 'Sarah Mayor',
    jenisKelamin: 'Perempuan',
    lingkungan: 'LINGKUNGAN KOTAWI',
    tanggalLahir: '2001-08-22',
    telepon: '081234567891',
    alamat: 'Waisai, Jl. Port Kotawi No. 12',
    status: 'Aktif',
    tanggalDaftar: '2024-01-15',
  },
  {
    id: '3',
    nama: 'Petrus Sanadi',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN TELMA UTARA',
    tanggalLahir: '1995-11-30',
    telepon: '081398765432',
    alamat: 'Kampung Telma, Blok A',
    status: 'Aktif',
    tanggalDaftar: '2024-02-05',
  },
  {
    id: '4',
    nama: 'Maria Mambrasar',
    jenisKelamin: 'Perempuan',
    lingkungan: 'LINGKUNGAN TELMA UTARA',
    tanggalLahir: '1999-02-14',
    telepon: '081398765433',
    alamat: 'Kampung Telma, Gg. Damai',
    status: 'Aktif',
    tanggalDaftar: '2024-02-10',
  },
  {
    id: '5',
    nama: 'Amandus Sauyai',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN TELMA SELATAN',
    tanggalLahir: '1997-07-07',
    telepon: '081255554444',
    alamat: 'Telma Selatan, Dekat Gereja',
    status: 'Aktif',
    tanggalDaftar: '2024-02-28',
  },
  {
    id: '6',
    nama: 'Christina Mayor',
    jenisKelamin: 'Perempuan',
    lingkungan: 'LINGKUNGAN WAIGEO SELATAN',
    tanggalLahir: '2000-05-18',
    telepon: '082188887777',
    alamat: 'Kampung Saonek, Waigeo Selatan',
    status: 'Aktif',
    tanggalDaftar: '2024-03-01',
  },
  {
    id: '7',
    nama: 'Daniel Wanma',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN WAIGEO SELATAN',
    tanggalLahir: '2003-12-05',
    telepon: '082188887778',
    alamat: 'Kampung Warsambin',
    status: 'Aktif',
    tanggalDaftar: '2024-03-15',
  },
  {
    id: '8',
    nama: 'Yuliana Gaman',
    jenisKelamin: 'Perempuan',
    lingkungan: 'LINGKUNGAN ALIF KORERE',
    tanggalLahir: '1996-09-09',
    telepon: '081122334455',
    alamat: 'Kabila, Alif Korere',
    status: 'Aktif',
    tanggalDaftar: '2024-03-20',
  },
  {
    id: '9',
    nama: 'Fransiskus Mayor',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN WAIGEO BARAT KEPULAUAN',
    tanggalLahir: '1994-10-25',
    telepon: '081244332211',
    alamat: 'Pulau Pam, Waigeo Barat Kepulauan',
    status: 'Aktif',
    tanggalDaftar: '2024-04-02',
  },
  {
    id: '10',
    nama: 'Florentina Mayor',
    jenisKelamin: 'Perempuan',
    lingkungan: 'LINGKUNGAN WAIGEO BARAT KEPULAUAN',
    tanggalLahir: '2002-01-15',
    telepon: '081244332212',
    alamat: 'Pulau Pam, Gg. Bahari',
    status: 'Aktif',
    tanggalDaftar: '2024-04-05',
  },
  {
    id: '11',
    nama: 'George Mayor',
    jenisKelamin: 'Laki-laki',
    lingkungan: 'LINGKUNGAN WAIGEO BARAT DARATAN',
    tanggalLahir: '1997-03-11',
    telepon: '087812123434',
    alamat: 'Manyaifun, Waigeo Barat Daratan',
    status: 'Aktif',
    tanggalDaftar: '2024-04-18',
  }
];

export const INITIAL_PENGGUNA: Pengguna[] = [
  {
    id: 'p1',
    nama: 'Rian F. K. Mayor, S.Kom',
    email: 'rianmayor096@gmail.com',
    peran: 'Administrator',
    status: 'Aktif',
  },
  {
    id: 'p2',
    nama: 'Pdt. Herman Wandamen, S.Th',
    email: 'herman.wandamen@gmail.com',
    peran: 'Operator',
    status: 'Aktif',
  },
  {
    id: 'p3',
    nama: 'Yance Syaranamual',
    email: 'yance.sya@gmail.com',
    peran: 'Operator',
    status: 'Non-aktif',
  },
];
